### ISSUE TITLE
Heatmap not working

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo-status#22] opened 2020-03-18 22:13 UTC
original report by @Lineflyer 
> https://www.cgeo.org/heatmap
>
> It does not show data, only the user count.

From what I can see, the websocket doesn't output any data: wss://status.cgeo.org/api/locations

![Screenshot from 2020-03-18 22-50-09](https://user-images.githubusercontent.com/176794/77012188-c70b9c00-696d-11ea-91d3-a880da57c599.png)

On preliminary discussion on cgeo-dev group, @samueltardieu said:
> The distribution model of geolocation data (from MaxMind) has changed.

@samueltardieu Thanks for taking it :+1:

**Comment by samueltardieu** [comment] 2020-03-18 22:15
I already know indeed what the problem is and I have started working on it some time ago. I need ~1 hour of work to fix this, I hope I'll be able to find some time before the end of the week.

**Comment by Lineflyer** [comment] 2020-03-18 22:25
No need to hurry...its just a nice gimmick for us, nothing important.
But thanks for that fast reaction and 

Best regards to Paris, 

Lars

Am 18.03.2020 23:16, schrieb Samuel Tardieu:

> I already know indeed what the problem is and I have started working on it some time ago. I need ~1 hour of work to fix this, I hope I'll be able to find some time before the end of the week. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/cgeo/cgeo-status/issues/22#issuecomment-600886008
[2]

**Comment by samueltardieu** [comment] 2020-03-19 09:55
Fix has been deployed.

**Closed** 2020-03-19 09:55 UTC
Labels: bug
